name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add RELEASE_TOKEN="$RELEASE_TOKEN" --repo ditto-assistant/dittobench-datagen
